version: '3'
services:
  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: temppass
      POSTGRES_DB: pos
    volumes:
      - ./main/data:/var/lib/postgresql/data

  main:
    restart: always
    build: ./main
    volumes:
      - ./main:/usr/src/app/
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 pos:app
    depends_on:
      - db